#!/bin/bash
# Partly courtesy of http://www.ibm.com/developerworks/linux/library/l-initrd.html


# Housekeeping...
rm -f /tmp/ramdisk.img
rm -f /tmp/ramdisk.img.gz

# Ramdisk Constants
RDSIZE=4096
BLKSIZE=1024
#ROOTDEV="sda5"
ROOTDEV=$(awk '/^[ \t]*[^#]/ { if ($2 == "/") { print $1; }}' /etc/fstab | cut -d/ -f3)

# Create an empty ramdisk image
dd if=/dev/zero of=/tmp/ramdisk.img bs=$BLKSIZE count=$RDSIZE

# Make it an ext2 mountable file system
/sbin/mke2fs -F -m 0 -b $BLKSIZE /tmp/ramdisk.img $RDSIZE

# Mount it so that we can populate
mount /tmp/ramdisk.img /mnt/initrd -t ext2 -o loop=/dev/loop0

# Populate the filesystem (subdirectories)
mkdir /mnt/initrd/bin
mkdir /mnt/initrd/sys
mkdir /mnt/initrd/dev
mkdir /mnt/initrd/proc
mkdir /mnt/initrd/lib
mkdir /mnt/initrd/new_root

# Grab busybox and create the symbolic links
cd /mnt/initrd/bin
cp /home/mcclurem/fuck/busybox-1.13.2/busybox .
#cp /usr/local/src/busybox-1.1.1/busybox .
ln -s busybox ash
ln -s busybox mount
ln -s busybox mkdir
ln -s busybox echo
ln -s busybox ls
ln -s busybox cat
ln -s busybox ps
ln -s busybox dmesg
ln -s busybox sysctl
ln -s busybox pivot_root

cd

# Grab the necessary dev files
cp -a /dev/console /mnt/initrd/dev
cp -a /dev/ramdisk /mnt/initrd/dev
cp -a /dev/ram0 /mnt/initrd/dev
cp -a /dev/null /mnt/initrd/dev
cp -a /dev/tty1 /mnt/initrd/dev
cp -a /dev/tty2 /mnt/initrd/dev
cp -a /dev/$ROOTDEV /mnt/initrd/dev

# Equate sbin with bin
cd /mnt/initrd
ln -s bin sbin
cd 

# Create the init file
cat >> /mnt/initrd/linuxrc << EOF
#!/bin/ash
echo
echo "Simple initrd is active"
echo
mount -t proc /proc /proc
mount -t sysfs none /sys
mount /dev/$ROOTDEV /new_root
cd /new_root
echo 0x0100 >/proc/sys/kernel/real-root-dev
pivot_root . ./mnt/initrd # same as in initrd.txt
#chroot . /sbin/init</dev/console 2>/dev/console # same as in initrd.txt
exec chroot . /sbin/init </dev/console >/dev/console 2>&1
#/bin/ash --login
EOF

chmod +x /mnt/initrd/linuxrc

# Finish up...
umount /mnt/initrd
gzip -9 /tmp/ramdisk.img
cp /tmp/ramdisk.img.gz /boot/ramdisk.img.gz
